netBarManageSys/urls.py
from django.contrib import admin
from django.urls import path
from netBarSys import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('mguser/', views.mguser, name='mguser'),
    path('logout/', views.logout, name='logout'),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('onlineuser/', views.onlineuser, name='onlineuser'),
    path('adduser/', views.adduser, name='adduser'),
    path('deluser/<user_id>', views.deluser, name='deluser'),
    path('forceoffline/<user_id>', views.forceoffline, name='forceoffline'),
    path('modifypsw', views.modifypsw, name='modifypsw'),
]

netBarSys/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    usertype = models.IntegerField(default=0)#0-顾客，1-管理员
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

class UserInfos(models.Model):
    user= models.OneToOneField(Users, on_delete=models.CASCADE)
    logintime=models.DateTimeField('login in time',default='1920-01-01 00:00:00')#登录时间,初始值赋值一个极早的时间，代表无效值
    lastlogouttime=models.DateTimeField('last login out time',default='1920-01-01 00:00:00')#上次登出时间,初始值赋值一个极早的时间，代表无效值
    onlinetime=models.IntegerField(default=0)#在线时间单位分钟，当该值超过240，强制下线
    onlinetimestr=models.CharField(max_length=50,default="不到1分钟")#在线时间字符串形式
    state=models.IntegerField(default=0)#顾客状态0-offline normal,1-online normal 2 管理员手动强制下线  3、超时自动强制下线
    fee=models.IntegerField(default=0)#费用

netBarSys/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Users,UserInfos
from apscheduler.schedulers.background import BackgroundScheduler
from datetime import datetime
from django.db.models import Q 
import json 

fee_hafhour=5 #费用5元/半小时

#************************************************渲染相关函数****************************************
def index(request):
    if request.method == 'POST':
        tempname = request.POST['name']
        password =  request.POST['password']
        usertype=int((request.POST['usertype']))
        # 查询用户是否在数据库中
        print("%s,%s,%d"%(tempname,password,usertype))
        if Users.objects.filter(name=tempname).exists():
            user=Users.objects.get(name=tempname)

            if user.password==password and int(user.usertype)==usertype:
                if request.session.get("is_login")=='true' and request.COOKIES.get('name')==tempname:
                    return HttpResponseRedirect(reverse('home'))
                else:
                    request.session['is_login'] = 'true'
                    request.session['name'] = 'name',
                    if user.usertype==1:
                        onlineuserinfo_list = UserInfos.objects.filter(state=1).order_by('-logintime')
                        offlineuserinfo_list = UserInfos.objects.filter(~Q(state=1)).order_by('-lastlogouttime')
                        context = {'onlineuserinfo_list': onlineuserinfo_list,'offlineuserinfo_list': offlineuserinfo_list}
                        response=render(request, 'homepage_a.html',context)#跳到管理员首页界面
                    else:
                        userinfo = UserInfos.objects.get(user = user)
                        if userinfo.state==3:
                            messages.add_message(request,messages.ERROR,'距离你上次长时间上网还不到2个小时，请再休息一会')
                            return render(request, 'index.html')
                        else:
                            userinfo.state=1
                            userinfo.logintime=datetime.now()
                            userinfo.onlinetime=0
                            userinfo.onlinetimestr="不到1分钟"
                            userinfo.fee=fee_hafhour
                            userinfo.save()
                            context = {'userinfo': userinfo}
                            response=render(request, 'homepage.html',context)#跳到顾客首页界面
                #set cookie
                trans_uname = user.name.encode('utf-8').decode('latin-1')#转一下解决cooki不能设置中文的问题
                response.set_cookie('name', trans_uname)
                return response
            else:
                messages.add_message(request,messages.ERROR,'用户密码或身份类型错误')
                return render(request, 'index.html')
        else:
            messages.add_message(request,messages.ERROR,'用户不存在')
            return render(request, 'index.html')
    return render(request, 'index.html')

def home(request):#去首页
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
       trans_cook=cook.encode('latin-1').decode('utf-8')
    user = Users.objects.get(name = trans_cook)
    if user.usertype == 0:
        userinfo = UserInfos.objects.get(user = user)
        context = {'userinfo': userinfo}
        return render(request, 'homepage.html',context)
    elif user.usertype == 1:
        onlineuserinfo_list = UserInfos.objects.filter(state=1).order_by('-logintime')
        offlineuserinfo_list = UserInfos.objects.filter(~Q(state=1)).order_by('-lastlogouttime')
        context = {'onlineuserinfo_list': onlineuserinfo_list,'offlineuserinfo_list': offlineuserinfo_list}
        return render(request, 'homepage_a.html',context)


def onlineuser(request):#显示在线用户
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:',  trans_cook)
    user = Users.objects.get(name = trans_cook)
    userinfo_list=UserInfos.objects.filter(state=1).order_by('-publishtime') 
    userinfo_list=UserInfos.objects.filter().order_by(onlinetime) 
    context = {'userinfo_list': userinfo_list}
    return  render(request,'onlineuser.html',context )

def mguser(request):#管理用户
    cook = request.COOKIES.get('name')
    print('cook:', cook)
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    user = Users.objects.get(name = trans_cook)
    user_list=Users.objects.filter(usertype=0).order_by('-id')#只管理非管理员账户
    context = {'user_list': user_list}
    return  render(request,'mguser.html',context )

def adduser(request):#添加用户
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:', trans_cook)
    if request.method == 'POST':
        tempname = request.POST['name']
        temppsw = request.POST['password']

        if Users.objects.filter(name=tempname).exists():
            messages.add_message(request,messages.ERROR,'该账户已经存在')
            return HttpResponseRedirect(reverse('mguser'))
        else:
            user=Users(name = tempname,password=temppsw)
            user.save()
            userinfo=UserInfos(user=user)#初始时间赋值
            userinfo.save()
            return HttpResponseRedirect(reverse('mguser'))
    return HttpResponseRedirect(reverse('mguser'))

def deluser(request,user_id):#删除用户
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:', trans_cook)
    temp_id=user_id
    user = Users.objects.get(id=temp_id)
    UserInfos.objects.filter(user=user).delete()
    Users.objects.filter(id=temp_id).delete()
    return HttpResponseRedirect(reverse('mguser'))

def logout(request):#退出
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:', trans_cook)
    user = Users.objects.get(name = trans_cook)
    if user.usertype==0:
        userinfo = UserInfos.objects.get(user = user)
        if userinfo.state==1:
            userinfo.state=0
        userinfo.lastlogouttime=datetime.now()
        userinfo.save()
    request.session.delete()
    request.session.flush() 
    response=render(request, 'index.html')
    response.delete_cookie('name')
    return response

def myinfo(request):#我的界面
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:', trans_cook)
    user = Users.objects.get(name = trans_cook)
    if user.usertype==0:
        userinfo = UserInfos.objects.get(user = user)
        content={'my':user,"userinfo":userinfo}
        return render(request, 'my.html',content)
    else:
        content={'my':user}
        return render(request, 'my_a.html',content)

def modifypsw(request):#修改密码
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:', trans_cook)
    user = Users.objects.get(name = trans_cook)
    if request.method == 'POST':
        temp_psw=request.POST.get('password')
        user.password=temp_psw
        user.save()
        return HttpResponseRedirect(reverse('myinfo'))
    if user.usertype==0:
        userinfo = UserInfos.objects.get(user = user)
        content={'my':user,"userinfo":userinfo}
        return  render(request,'modifypsw.html',content)
    else:
        content={'my':user}
        return  render(request,'modifypsw_a.html',content)

def forceoffline(request,user_id):#强制下线
    cook = request.COOKIES.get('name')
    if cook == None:
        return  render(request, 'index.html')
    else:
        trans_cook=cook.encode('latin-1').decode('utf-8')
    print('cook:', trans_cook)
    user = Users.objects.get(name = trans_cook)
    if user.usertype==0:
        return  render(request, 'index.html')
    temp_id=user_id
    forceuser=Users.objects.get(id=temp_id)
    forceoffuser = UserInfos.objects.get(user=forceuser)
    forceoffuser.state=2 #将状态设置为强制下线，定时器中检测到该状态后，会强制顾客退出
    forceoffuser.save()
    return HttpResponseRedirect(reverse('home'))

#************************************************逻辑处理相关函数****************************************
def timeValied(time):
    inittime=datetime(1980,1,2,0,0,0)
    if time<inittime:
        return False
    else:
        return True
        
#定时任务，定时更新onlinetime
def timfunc():
    userinfo_list = UserInfos.objects.all()
    for userinfo in userinfo_list:
        if userinfo.state==1 and timeValied(userinfo.logintime):
            userinfo.onlinetime=int((datetime.now()-userinfo.logintime).total_seconds()/60)
            print("userinfo.onlintime =%d " % userinfo.onlinetime)
            if userinfo.onlinetime>60:
                userinfo.onlinetimestr=""+str(int(userinfo.onlinetime/60))+"小时"+str(int(userinfo.onlinetime%60))+"分钟"
            elif userinfo.onlinetime>1:
                userinfo.onlinetimestr=str(int(userinfo.onlinetime))+"分钟"
            else:
                userinfo.onlnietimestr="不到1分钟"
            userinfo.fee=int(userinfo.onlinetime/30+1)*fee_hafhour#不满半小时按半小时算

            if userinfo.onlinetime>(60*4): #如果上网时间大于4小时强制下线
                print("userinfo.onlinetime>4hour set userinfo.state=3")
                userinfo.state=3
        elif userinfo.state==3 and timeValied(userinfo.lastlogouttime):
            print(userinfo.lastlogouttime)
            offlinetime=int((datetime.now()-userinfo.lastlogouttime).total_seconds()/60) #距离上次超时退网的时间差

netBarSys/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
     <!-- 使用CSS样式来控制div布局 -->
     <style type="text/css">
        /*定义全局的div布局*/
        div#global{
            /*设置宽度，设置百分比可以根据浏览器自适应宽度*/
            width: 100%;
            /*设置高度，950px是设置是实体高度，不能自适应的*/
            height: 1000px;
            /*设置背景颜色*/
            background-color:white; 
            background-size: cover;
            background-repeat:repeat
        }
        /*定义菜单样式*/
        #topmenucenter{
            width: 80%;
            height: 52px;
            font-size:16px;
            background-color:rgb(177, 207, 228);
            border:0;
            font-weight: bold;
            float:middle;
            vertical-align: middle;
        }
         /*定义右侧菜单样式*/
        #topmenuright{
            width: 20%;
            height: 52px;
            font-size:16px;
            background-color:rgb(177, 207, 228);
            border:0;
            font-weight: bold;
            float:right;
            vertical-align: middle;
        }
        #heading{
            width: 100%;
            height: 30px;
            font-size:20px;
            border:0;
            background-color:gainsboro;
            vertical-align: top;
        }
        #content_body{
            width: 100%;
            height: 900px;
            float: middle;
            font-size:30px;          
        }
        #link{
            font-size:20px;
            padding: 6px;
            text-decoration:none;
            color:gray;          
        }
        #selectedlink{
            font-size:20px;
            padding: 6px;
            text-decoration:none;
            color:black;         
         }
         #link_center{
            font-size:24px;
            padding: 6px;
            text-decoration:none;
            color:gray;          
        }
        #selectedlink_center{
            font-size:24px;
            padding: 6px;
            text-decoration:none;
            color:black;         
         }
        #pcontent{
            font-size:28px;
            color:darkslategrey
        }
        #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
    </style>
    {% block style %}
    {% endblock %}
</head>
<style>       
	html,body{text-align:center;margin:auto;}
</style>
<body>
    <!-- 在这里控制全局的页面，定义div的id是"global" -->
    <div id="global">
        <div id="heading" align="left">
            {% block heading %}
               <label >AA网吧系统</label>
            {% endblock %}
        </div>
        <div id="topmenuright" >
            {% block topmenuright %}
                <a id =link_my  href="{% url 'myinfo' %}">我的</a> 
                <a id =link_out href="{% url 'logout' %}" >退出</a> 
            {% endblock %}
        </div>
        <div id="topmenucenter">
            {% block topmenucenter %}
            {% endblock %}
        </div>
        <div id="content_body">
            <div>
                {% for message in messages %}
                    <div class='alert alert-{{message.tags}}' style="color:coral">{{ message }}</div>
                {% endfor %}
            </div>
                {% block contentbody %}
                {% endblock %}
        </div>
    </div>
</body>
</html>

netBarSys/templates/homepage.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block topmenucenter %}
    <div style="padding:5px">
        <a id =selectedlink_center href="{% url 'home' %}">首页</a>
    </div>
{% endblock %}

{% block contentbody %}
<div id=textcontent>
    <table align="center">
        <tr>
            <td align="right" width="20%">上机时间：</td>
            <td align="left" width="80%">{{userinfo.logintime}}</td>
        </tr>
        <tr>
            <td align="right" width="20%">上机时长：</td>
            <td align="left" width="80%">{{userinfo.onlinetimestr}}</td>
        </tr>
        <tr>
            <td  align="right" width="20%">费用：</td>
            <td align="left" width="80%">{{userinfo.fee}}元</td>
        </tr>
        <tr>
            <td  align="right" width="20%" style="display: block"><label name="state" id= "state" style="display: none">{{userinfo.state}}</label></td>
            <td align="left" width="80%"><a id =link_out href="{% url 'logout' %}" >退出</a></td>
        </tr>
    </table>
</div>
<script>
     window.onload=function(){
        var state = document.getElementById('state').innerHTML;
        if (state==2){
            alert("你已被管理员强制下线");
            document.getElementById("link_out").click();
        }
        if (state==3){
            alert("休息一下，2小时后登陆");
            document.getElementById("link_out").click();
        }
    }
    setTimeout("timer()",1000*30);
    function timer(){
        document.getElementById("selectedlink_center").click();
        setTimeout("timer()",1000*30);//每30s分钟刷新依次网页
    }
</script>
{% endblock %}

netBarSys/templates/homepage_a.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %} 
    <style type="text/css">
        #textcontent {
        width: 80%;
        height: auto;
        font-size:20px;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
    </style>
{% endblock %}

{% block topmenucenter %}
    <div style="padding:5px">
        <a id =selectedlink_center href="{% url 'home' %}">首页</a>
        <a id =link_center  href="{% url 'mguser' %}">用户管理</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <div style="margin: 0% 5% 0% 5%">
        <div id=textcontent>
            <h4>在线用户</h4>
            <table align="center">
                <tr>
                    <td width=20% align="left">用户</td>
                    <td width=30% align="left">&nbsp&nbsp上机时间</td>
                    <td width=20% align="left">&nbsp&nbsp上机时长</td>
                    <td width=15% align="left">&nbsp&nbsp费用</td>
                    <td width=10% align="left">&nbsp&nbsp管理</td>
                </tr>
            {% for userinfo in onlineuserinfo_list.all %}
                <tr>
                    <td width=20% align="left">{{ userinfo.user.name }}</td>
                    <td width=30% align="left">&nbsp&nbsp{{ userinfo.logintime }}</td>
                    <td width=20% align="left">&nbsp&nbsp{{ userinfo.onlinetimestr }}</td>
                    <td width=15% align="left">&nbsp&nbsp{{ userinfo.fee }}元</td>
                    <td width=15% align="left">&nbsp&nbsp<a href="{% url 'forceoffline' userinfo.user.id %}">下线</a></td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div id=textcontent>
            <h4>离线用户</h4>
            <table align="center">
                <tr>
                    <td width=25% align="left">用户</td>
                    <td width=25% align="left">&nbsp&nbsp密码</td>
                    <td width=30% align="left">&nbsp&nbsp上次登出时间</td>
                    <td width=20% align="left">&nbsp&nbsp状态</td>
                </tr>
            {% for userinfo in offlineuserinfo_list.all %}
                <tr>
                    <td width=25% align="left">{{ userinfo.user.name }}</td>
                    <td width=25% align="left">&nbsp&nbsp{{ userinfo.user.password }}</td>
                    <td width=30% align="left"><label name="lastlogout" id= "{{userinfo.lastlogouttime}}"></td>
                    <td width=20% align="left">&nbsp&nbsp<label name="state" id= "state{{userinfo.state}}"></label></td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <script>
            window.onload=function(){
            var states = document.getElementsByName('state');
            for( var i=0; i<states.length; i++){
                var state=states[i];
                if(state.id.indexOf("0")!=-1){
                    state.innerText="离线";
                }
                else if(state.id.indexOf("1")!=-1){
                    state.innerText="在线";
                }
                else if(state.id.indexOf("2")!=-1){
                    state.innerText="强制下线";
                }
                else if(state.id.indexOf("3")!=-1){
                    state.innerText="超时下线";
                }
            }
            var lastlogouts = document.getElementsByName('lastlogout');
            for( var i=0; i<lastlogouts.length; i++){
                var lastlogout=lastlogouts[i];
                if(lastlogout.id.indexOf("1920")!=-1){
                    lastlogout.innerText="未登陆过";
                }
                else{
                    lastlogout.innerText=lastlogout.id;
                }
            }
        }
        setTimeout("timer()",1000*30);
        function timer(){
            document.getElementById("selectedlink_center").click();
            setTimeout("timer()",1000*30);
        }
        </script>
    </div>
{% endblock %}

netBarSys/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
     <!-- 使用CSS样式来控制div布局 -->
     <style type="text/css">
        /*定义全局的div布局*/
        #content{
            width: 100%;
            height: 800px;
            margin:200px auto;
        }
        html,body{text-align:center}
        input,select{height:30px; width:200px; vertical-align:left;}

    </style>
</head>
<body>
    <div id=content>
        <h2>AA网吧管理系统</h2>
        <div>
            {% for message in messages %}
                <div class='alert alert-{{message.tags}}' style="color:coral">{{ message }}</div>
            {% endfor %}
        </div>
        <form action="{% url 'index' %}" method="post" name='login'>{% csrf_token %}
           <table align="center">
                <tr>
                    <td>账户：</td>
                    <td><input type="text" id="id_name" name="name" placeholder="用户名" autofocus required  /></td>
                </tr>
                <tr>
                    <td>密码：</td>
                    <td><input type="password" id="id_password" placeholder="密码" name="password" required  /></td>
                </tr>
                <tr>
                    <td>角色：</td>
                    <td>
                        <select id="usertype"  name="usertype" panelHeight="auto" >
                            <option value=0>会员</option>
                            <option value=1>管理员</option>
                        </select> 
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="登录" >
                    </td>
                </tr>
           </table>     
    </form>
</div>
</body>
</html>

netBarSys/templates/mguser.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block topmenucenter %}
    <div style="padding:5px">
        <a id =link_center href="{% url 'home' %}">首页</a>
        <a id =selectedlink_center  href="{% url 'mguser' %}">用户管理</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <div style="margin: 0% 10% 0% 10%">
        <div  style="width:100%; height:100px">
            <h4 align="left">创建账户</h4>
            <form action="{% url 'adduser' %}" method="post" name="adduser">{% csrf_token %}
                <table>
                    <td width="40%">账号<input type="text"  name="name" style="height:30px"></td>
                    <td width="40%">密码:<input type="text"  name="password" style="height:30px"></td>
                    <td width="20%"><input type="submit" value="创建账户" style="height:30px"></td>
                </table>
            </form>
        </div>
        <br/>
        <br/>
        <div style="width:100%; height:500px">
            <h4 align="left">已有账户</h4>
            <form action="{% url 'mguser' %}" method="post" name='mguser'>{% csrf_token %}
                <table>
                    <tr>
                        <td width=35% style="font-weight: bold">账号</td>
                        <td width=35% style="font-weight: bold">密码</td>
                        <td width=30%></td>
                    </tr>
                    {% for user in user_list.all %}
                        <tr>
                            <td width=35%>{{user.name }}</td>
                            <td width=35%>{{ user.password }}</td>
                            <td width=30%><a href="{% url 'deluser' user.id %}">删除</a></td>
                        </tr>
                    {% endfor %}
                </table>
            </form>
        </div>
    </div>
{% endblock %}

netBarSys/templates/modifypsw.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block topmenucenter %}
<div style="padding:20px">
    <a id =link_center href="{% url 'home' %}">首页</a>
</div>
{% endblock %}

{% block contentbody %}
<div style="margin: 0% 10% 0% 10%">
        <div style="width:100%; height:300px">
            <h4>我的->修改密码</h4>
            <form enctype='multipart/form-data' action="{% url 'modifypsw' %}" method="post" name='modifypsw' >{% csrf_token %}
                <table style="margin:0% 0% 0% 0%;width:100%;" vertical-align=left>
                    <tr align="left">
                        <td width="20%" align="right">账户:</td>
                        <td width="80%" align="left">{{ my.name }}</td>
                    </tr>
                    <tr>
                        <td width="20%" align="right">密码:</td>
                        <td width=80%" align="left"><input type="text"  name="password"   style="width:800px;height:32px"/></td>
                    </tr>
                    <tr>
                        <td width="20%"align="right"style="display: block"><label name="state" id= "state" style="display: none">{{userinfo.state}}</td>
                        <td width="80%" align="left"><input type="submit" value="确定" name="confirmmodifypsw" style="width:200px; height:30px;float:right" ></a></td>
                    </tr>
                </table>
                <a id =modifypsw href="{% url 'modifypsw' %}" style="display: none" >退出</a> 
            </form>
        </div>
    </div>
    <script>
        window.onload=function(){
           var state = document.getElementById('state').innerHTML;
           if (state==2){
                alert("你已被管理员强制下线");
               document.getElementById("link_out").click();
           }
           if (state==3){
                alert("休息一下，2小时后登陆");
               document.getElementById("link_out").click();
           }
       }
       setTimeout("timer()",1000*30);
       function timer(){
           document.getElementById("modifypsw").click();
           setTimeout("timer()",1000*30);//每30s分钟刷新依次网页
       }
   </script>
{% endblock %}

netBarSys/templates/modifypsw_a.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
    #pcontent{
        font-size:28px;
        color:darkslategrey
    }
</style>
{% endblock %}
{% block topmenucenter %}
    <div style="padding:20px">
        <a id =link_center href="{% url 'home' %}">首页</a>
        <a id =link_center  href="{% url 'mguser' %}">用户管理</a>  
    </div>
{% endblock %}

{% block contentbody %}
<div style="margin: 0% 10% 0% 10%">
        <div style="width:100%; height:300px">
            <h4>我的->修改密码</h4>
            <form enctype='multipart/form-data' action="{% url 'modifypsw' %}" method="post" name='modifypsw' >{% csrf_token %}
                <table style="margin:0% 0% 0% 0%;width:100%;" vertical-align=left>
                    <tr align="left">
                        <td width="20%" align="right">账户:</td>
                        <td width="80%" align="left">{{ my.name }}</td>
                    </tr>
                    <tr>
                        <td width="20%" align="right">密码:</td>
                        <td width=80%" align="left"><input type="text"  name="password"   style="width:800px;height:32px"/></td>
                    </tr>
                    <tr>
                        <td width="20%"align="right"style="display: block"><label name="state" id= "state" style="display: none">{{userinfo.state}}</td>
                        <td width="80%" align="left"><input type="submit" value="确定" name="confirmmodifypsw" style="width:200px; height:30px;float:right" ></a></td>
                    </tr>
                </table>
            </form>
        </div>
	</div>
{% endblock %}

netBarSys/templates/onlineuser.html
{% extends 'base.html' %}

{% block head %}  
<br/>
{% endblock %}

{% block style %}
<style>
    #link{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:gray;          
    }
    #selectedlink{
        font-size:20px;
        padding: 6px;
        text-decoration:none;
        color:black;         
    }
    
    #textcontent {
        width: 80%;
        height: auto;
        word-wrap:break-word;
        word-break:break-all;
        overflow: hidden;
        margin:5% auto
    }
    #pcontent{
        font-size:28px;
        color:darkslategrey
    }
</style>
{% endblock %}

{% block topmenucenter %}
    <div style="padding:20px">
        <a id =selectedlink_center href="{% url 'home' %}">首页</a>
        <a id =link_center href="{% url 'onlieuser' %}">在线用户</a> 
        <a id =link_center  href="{% url 'mguser' %}">用户管理</a> 
    </div>
{% endblock %}

{% block contentbody %}
    <div style="margin: 0% 5% 0% 5%">
        <form enctype='multipart/form-data' action="{% url 'searchuser' %}" method="post" name='searchuser' >{% csrf_token %}
            <table align="center">
                <tr>
                    <td><input type="text" id="search" name="search_content" placeholder="请输入您要搜索的用户名" style="width:600px; height:30px"/></td>
                    <td><input type="submit" name='search' value="搜索" style="width:80px; height:50px"></td>
            </table>
        </form>
        <div id=textcontent>
            <table align="center">
                <tr>
                    <td width=10%>用户</td>
                    <td width=20%>上机时间</td>
                    <td width=20%>下机时间</td>
                    <td width=20%>上机时长</td>
                    <td width=10%>费用</td>
                    <td width=10%>状态</td>
                    <td width=10%>管理</td>
                </tr>
            {% for userinfo in userinfo_list.all %}
                <tr>
                    <td>{{ userinfo.user.name }}</td>
                    <td>{{ userinfo.loginintime }}</td>
                    <td>{{ userinfo.lastLogouttime }}</td>
                    <td>{{ userinfo.onlinetime }}</td>
                    <td>{{ userinfo.fee }}</td>
                    <td><label id="id_state"></label></td>
                    <td>&nbsp&nbsp<a href="{% url 'pages:forceoffline' userinfo.user.id %}">强制下线</a></td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}